services:
  - type: web
    name: procureai-ai
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: ./AI-SERVICE
    plan: free
    region: singapore
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash-latest

  - type: web
    name: procureai-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: ./BACKEND
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: com.mysql.cj.jdbc.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.MySQL8Dialect
      - key: DDL_AUTO
        value: update
      - key: GEMINI_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://procureai-89869.web.app,https://procureai-89869.firebaseapp.com,http://localhost:5173
      - key: PYTHON_AI_ENABLED
        value: "true"
      - key: PYTHON_AI_URL
        sync: false
