services:
  - type: web
    name: procureai-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: com.mysql.cj.jdbc.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.MySQL8Dialect
      - key: DDL_AUTO
        value: update
      - key: GEMINI_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://procureai-89869.web.app,https://procureai-89869.firebaseapp.com,http://localhost:5173
